# fly.toml file generated for pwbackend on 2023-04-14T13:38:35+02:00

app = "pwbackend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[[mounts]]
  source = "json_storage"
  destination = "/var/data"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
