'use client'
import './styles/globals.css'
import Navigation from './components/Navigation';
import Footer from './components/Footer';
import { SessionProvider } from "next-auth/react"
import "./api/auth/[...nextauth]";
import UserLayout from '@/components/layouts/UserLayout'

import { SettingsConsumer, SettingsProvider } from '@/core/context/settingsContext'
import ThemeComponent from '@/core/theme/ThemeComponent'


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ Component, pageProps, children, session }) {



  return (
<html lang="en">
      <SessionProvider session={session}>
      <SettingsProvider>
            <SettingsConsumer>
              {({ settings }) => {
                return (
                  <ThemeComponent settings={settings}>
        <body>
        <UserLayout><div className="container mx-auto px-4">{children}</div></UserLayout>
        <Footer />
        </body>
                          </ThemeComponent>
                )
              }}
            </SettingsConsumer>
          </SettingsProvider>

      </SessionProvider>
    </html>
  )
}
